### ISSUE TITLE
how to get answer from new message as soon its ready ?

### ISSUE THREAD

**Issue by madruga8** [kudoai/chatgpt.js#101]
hello i could not figure out how to call send message and get the response right away. theres a way for it ?

**Comment by adamlui** [comment]
hey @madruga8 yes you can do it like this:

```js
chatgpt.send('hello')
await chatgpt.isIdle()
const response = await chatgpt.getLastResponse()
console.log(response)
```

**Comment by adamlui** [comment]
there will be a finished userguide soon that will mark which methods are async for your convenience

**Comment by adamlui** [comment]
you can view the work in progress here: https://github.com/kudoai/chatgpt.js/blob/main/docs/USERGUIDE.md

**Comment by madruga8** [comment]
thank you very much... this library looks very promising ! if i could give a suggestion would be a function/option to hide the chats generated by this library so the user separate his own chats from those generated by the extension on extensions that generates too many different chats to work.

**Comment by madruga8** [comment]
i made claude 2 100k analyse your code and asked the same now, and comes the idea how we could also have a library for poe.com since its performing so good ! 

<img width="609" alt="image" src="https://github.com/kudoai/chatgpt.js/assets/30551844/e85d28c6-73df-493a-9d26-f2c23465a6bb">

**Comment by madruga8** [comment]
just a note regarding poe.com... i already got a ban from them for using the chatgptbox repo that uses poes.com endpoints... so i think a safe solution os use only DOM in poe.com and not the endpoints that causes bans...

**Comment by adamlui** [comment]
Can I see what you made with the chatgpt.js one?

**Comment by madruga8** [comment]
> Can I see what you made with the chatgpt.js one?

i have made anything yet... im just a heavy user of some extensions like the chatgpt box.

**Comment by adamlui** [comment]
Hey @madruga8 did you happen to make anything yet? If not, can you tell me what other features besides hiding queries from chat history you want?
