### ISSUE TITLE
Resolve `'Cannot contact custom instructions endpoint'` on some `chatgpt.instructions.add()`s

### ISSUE THREAD

**Issue by adamlui** [KudoAI/chatgpt.js#138]

**Comment by adamlui** [comment]
@madkarmaa check it out, when the instruction was only 352 chars it logged:

![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/2c3f1e14-9001-4251-85a5-409fc2564910)

..but when it was shortened to one sentence, it worked:

![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/5d21c2f1-d3df-4aca-94fd-53c3ddc1b9f5)

**Comment by madkarmaa** [comment]
![Screenshot_2023-08-31-08-44-54-57_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/KudoAI/chatgpt.js/assets/100418457/b86e0c00-2587-45ba-832a-1d1eaca10bf3)

maybe the moderation doesn't allow jailbreaking-like prompts? try with a normal sentence as long as that one

**Comment by adamlui** [comment]
It's not a jailbreak that's the point of custom instructions (respond as a persona) here's a different one of equal length:

![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/61219ebf-ae93-440c-9345-a0579020cc01)

**Comment by madkarmaa** [comment]
can you try to paste that instruction using the website's UI and see if it works there?

**Comment by adamlui** [comment]
Indeed it does 
![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/6b25db81-e9d5-478b-a127-c14613e46c6e)

**Comment by adamlui** [comment]
After the last error, I went into UI and cleared the short anti-dan sentence, then tried the long sentence and it worked. But anytime I try the long original sentence, error appears

**Comment by madkarmaa** [comment]
no, I mean paste that same "persona" in menu > custom instructions > ChatGPT

**Comment by adamlui** [comment]
Even with "anti-dan" replaced

> Hello! You will be taking on the role of what i ask, and you task is pretty simple. Every question i ask you, you will respond with "I apoligize, but as a language model," And then you will make up a rule on why you cannot answer the question. You will answer in the format of "what i ask: [insert x]". If you understand and are willing to accept, say "Ok

**Comment by adamlui** [comment]
> no, I mean paste that same "persona" in menu > custom instructions > ChatGPT

Yes I said I went into UI that's what menu is, it works with no problem so something is wrong with the method

**Comment by madkarmaa** [comment]
seems a lot strange, I might say "rate limits" but yesterday, during my tests, I typed the methods really fast so that's not the case. I'll look into it

**Comment by adamlui** [comment]
Even short sentences no longer work:

![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/b06a14a0-40ac-4c66-a705-5ddfb108660a)

I just went into menu and cleared a bunch of text (but left one sentence by accident)  and adding 'Hello' works

**Comment by madkarmaa** [comment]
can you please provide a detailed explanation on how to reproduce this issue step by step?

**Comment by adamlui** [comment]
Check it out this time pasted in menu it gives violation error

![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/27ed2048-ae29-4e93-ba55-11fc8d3b6d7c)

**Comment by adamlui** [comment]
Also another interesting error just occurred as I was revising the saved instruction in-menu. I removed some quotes and saved with no problem. After removing the final quotes:

![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/f872e361-6aad-4a61-9848-06ca7bf109fe)

So it appears quotes help to thwart the content-violation engine

**Comment by madkarmaa** [comment]
so yea, it is moderation indeed. I _suppose_ the consequent errors happen because the moderation is still actively moderating you. I'll give it a detailed look into the issue anyways

**Comment by adamlui** [comment]
> so yea, it is moderation indeed. I _suppose_ the consequent errors happen because the moderation is still actively moderating you. I'll give it a detailed look into the issue anyways

But the first error is Request failed unlike the detailed moderation-related one here, so you should research what the specific trigger for first error is, then if confirm moderation-related you must add a disclaimer to not include certain words or content to the in-line instruction and userguide. Also can you confirm the 1-step action triggers the Request failed for you

**Comment by madkarmaa** [comment]
I confirm I get the 403 error

**Comment by madkarmaa** [comment]
yep, as I thought, 403 error code is triggered by moderation. here's the response to the web request @adamlui 

![image](https://github.com/KudoAI/chatgpt.js/assets/100418457/c6996521-d41c-4da8-ac2f-c79bdcaae8a3)

**Comment by adamlui** [comment]
But my original request results in "Request failed," do you get the detailed one instead?

**Comment by adamlui** [comment]
Ok I guess mysteyr is solved
