### ISSUE TITLE
Make `chatgpt.sidebar.append()` work

### ISSUE THREAD

**Issue by adamlui** [KudoAI/chatgpt.js#141]
It doesn't work for me

![Image](https://github.com/KudoAI/chatgpt.js/assets/10906554/cceb423d-b7c0-424a-b448-042776daf977)

**Comment by madkarmaa** [comment]
update the UI, remember it's a mutation observer. like, click on a button

**Comment by adamlui** [comment]
it doesn't work when clicking buttons either the labels are missing
![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/12ab654b-d2cf-47e7-96ae-35e5807c4497)
also it should just work without having to click or do anything if it's supposed to be a method for simply inserting an element

**Comment by adamlui** [comment]
Actually it worked with button after click, but can you make it work right away instead

**Comment by adamlui** [comment]
Also the notese are still very unclear, 

>         // + custom attributes: 'icon' for 'button' | 'items' for 'select'

Can you format it like i did in alert so user knows exactly what to type?

**Comment by madkarmaa** [comment]
> it doesn't work when clicking buttons either the labels are missing ![image](https://user-images.githubusercontent.com/10906554/265043827-12ab654b-d2cf-47e7-96ae-35e5807c4497.png) also it should just work without having to click or do anything if it's supposed to be a method for simply inserting an element

the `<select>` element is only supposed to take in options. I can add a default option like "chatgpt.js option"

**Comment by adamlui** [comment]
Also can you change select to dropdown

**Comment by madkarmaa** [comment]
> Also the notese are still very unclear,
> 
> > ```
> >     // + custom attributes: 'icon' for 'button' | 'items' for 'select'
> > ```
> 
> Can you format it like i did in alert so user knows exactly what to type?

wdym?

```js
        append: function(element, attrs = {}) {
        // element = 'button' | 'select' REQUIRED (no default value)
        // attrs = { ... } 'icon', 'label', 'onclick' for 'button' | 'items[]' for 'select' (defaults to empty)
```

https://github.com/KudoAI/chatgpt.js/blob/main/chatgpt.js#L1454-L1456

**Comment by madkarmaa** [comment]
> Also can you change select to dropdown

sure

**Comment by adamlui** [comment]
Ok maybe I'm looking at your old commit, but still it needs to be clear what each one expects i.e. icon is a URL, label are words, onclick is a function, and items[] is unclear, so if you look at the way I made it clear in alert then you should do it like that

**Comment by madkarmaa** [comment]
to make it work instantly I can convert [this](https://github.com/KudoAI/chatgpt.js/blob/main/chatgpt.js#L1438-L1447) into a method and call it immediately

**Comment by adamlui** [comment]
The activateObserver is already unuseful to the lib user, you should try to not have to define that either

**Comment by madkarmaa** [comment]
then there's only 1 solution: trigger the observer. how can that be done? maybe by changing an attribute in a page element(?)

**Comment by adamlui** [comment]
Yes change something trivial
