### ISSUE TITLE
funding

### ISSUE THREAD

**Issue by mejango** [kudoai/chatgpt.js#158]
Hey yall, 
Curious to get in touch with whoever is managing this project
https://juicebox.money/v2/p/588 (0xad029Eb29Dc085ed2BC83c59eaC72B5BF0493EDE)

Excited to help make it successful, but first want to confirm who owns it.

**Comment by adamlui** [comment]
Hey @mejango! The project was created by me as part of instructions from Artizen CEO (they are partnered and do match funding). I am a relative noob to Web3 fundraising though, so have no idea how all of it works. If you have ideas how to optimize the project on juicebox, that would be really helpful!

**Comment by mejango** [comment]
got it! great. I passed along feedback to the team that it should be easier to add contact/verification info on the juicebox page.
Sounds also like filip is helping you out, he's great.
Exciting!
