### ISSUE TITLE
Export current temporary chat without hitting API

### ISSUE THREAD

**Issue by thomasgauthier** [KudoAI/chatgpt.js#166]
I would like to use this extension to save the current chat as json file.

I've noticed that when chat history is set to off, methods like `getLastResponse` will return messages from my last saved conversation, not the current temporary conversation.

I'm interested in getting the markdown content of messages. I know it exists locally as the copy to clipboard message at the bottom of each response will put it in your keyboard without hitting any API endpoint.

Is this something that could be supported?

Visual reference:
![Temporary chat](https://github.com/KudoAI/chatgpt.js/assets/9730392/62126c5b-866a-4147-ad1c-18a7cba52efe)
![copy to clipboard](https://github.com/KudoAI/chatgpt.js/assets/9730392/fc788fa2-444c-4838-b19f-893df166e6af)

**Comment by adamlui** [comment]
Hey @thomasgauthier indeed it is already supported, both the clipboard icon function and chatgpt.js uses front-end method to get the response (then API method was introduced) but I patched that method to work again, it is

`chatgpt.response.getFromDOM(1|2|3|'last')` or `chatgpt.getResponseFromDOM(1|2|3|'last')`

![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/ef05e3c0-ca77-4d3b-94af-bc83cf7f6b99)

... which works while function is called on the chat page. Also could you share what you're building if you want when you're done?
