### ISSUE TITLE
Failed to load as a Greasemonkey script 

### ISSUE THREAD

**Issue by pramatias** [KudoAI/chatgpt.js#178]
I tried running the following script, and every object prefixed with: chatgpt. returns null. Greasemonkey did download the minified chatgpt js file, but it cannot work at all with the object chatgpt . chatgpt.getLastReply, chatgpt.getLastResponse all return null. 

// ==UserScript==
// @name          ChatGPT Userscript
// @description   A Greasemonkey template to start using chatgpt.js like a boss
// @author        chatgpt.js
// @namespace     https://chatgpt.js.org
// @version       2024.1.28
// @match         https://chat.openai.com/*
// @icon          https://raw.githubusercontent.com/kudoai/chatgpt.js-greasemonkey-starter/main/media/images/icons/robot/icon48.png
// @require       https://cdn.jsdelivr.net/npm/@kudoai/chatgpt.js@2.6.4/dist/chatgpt-2.6.4.min.js
// @grant         GM_getValue
// @grant         GM_setValue
// @noframes
// @homepageURL   https://github.com/kudoai/chatgpt.js-greasemonkey-starter
// ==/UserScript==

(async () => {
		// Init config
    console.log("Inside async ");
  
    // Print chatgpt.js methods
    await chatgpt.isLoaded(); 
    console.log("Past GPT loading ");

    function logHello() {
	       (async () => {
      					console.log("Hello again");
           try {
              let lastResponse = await chatgpt.getLastReply();
             
              if (typeof lastResponse === 'string') {
                  console.log("Hello " + lastResponse);
              } else {
                  console.error("Hello Error: lastResponse is not a string");
              }   

                   console.log("Hello " + lastResponse);
              } catch (error) {
                  console.error("Async Hello Error:", error);
              }
          })();
  	 }
    // Run the logger when the DOM is ready
    window.addEventListener('DOMContentLoaded', logHello());
  
})();

**Comment by adamlui** [comment]
hi @paramtias thank you for opening the issue. The synonymization routine that generates function aliases like `getLastReply` is bugged so that one specifically doesn't work (nearly all the other ones generated using https://github.com/KudoAI/chatgpt.js/blob/main/data/function-aliases.json work) but you can reference the [userguide](https://github.com/KudoAI/chatgpt.js/blob/main/docs/USERGUIDE.md) for the names of the root methods, in this case it is `getLastResponse`

But I just tested it, there is a new key error probably because OpenAI updated the API so I have to fix it first, but check out the other methods in the userguide

**Comment by adamlui** [comment]
@pramatias I think this key error is recent like past couple days, for some reason I cannot send second messages to ChatGPT 

![image](https://github.com/KudoAI/chatgpt.js/assets/10906554/e84b3fda-bff6-4bc0-867a-bb9688030322)

**Comment by pramatias** [comment]
Hello, @adamlui, thanks for the reply. 

I am writing my own javascript handler of the ChatGpt webui, because i need something much simpler than ChatGPT.js. I am stuck right now, because the the webui, doesn't activate the submit button, by just pasting text using jquery selectors. Even jquery keypress, the do not activate the button. 

Any idea how to solve something like that?

**Comment by pramatias** [comment]
Hello, @adamlui thanks for the reply. If the issue is fixed, i close the issue.
