### ISSUE TITLE
Response is empty

### ISSUE THREAD

**Issue by gadelkareem** [KudoAI/chatgpt.js#302]
I am using ChatGPT teams, URL: https://chatgpt.com/c/66f427ae-7934-800e-b4cc-ccbed4722d64

All the get response functions are returning empty:

![Screenshot 2024-09-25 at 5 11 54 PM](https://github.com/user-attachments/assets/ca07af99-79bd-4e27-a129-982ad14cf03c)
<img width="994" alt="Screenshot 2024-09-25 at 5 15 45 PM" src="https://github.com/user-attachments/assets/172668d8-303c-4896-87c7-4a67dfb252d4">

**Comment by adamlui** [comment]
Thanks for the helpful detailed screenshots @gadelkareem! I fixed it and all the methods you typed work again:

![image](https://github.com/user-attachments/assets/feacde56-1986-4198-9304-b068ff934d11)

The latest jsDelivr URL is https://cdn.jsdelivr.net/npm/@kudoai/chatgpt.js@3.3.2/dist/chatgpt.min.js

**Comment by adamlui** [comment]
Also do you think an options obj would be easier or harder to use?

e.g.

`chatgpt.getChatData({ chat: 'latest', details: 'msg', sender: 'both', msg: 'latest' })`

vs. the current

`chatgpt.getChatData('latest', 'msg', 'both', 'latest')`

**Comment by gadelkareem** [comment]
Thanks @adamlui for prompt response. I am not sure if it is on my end but now the `chatgpt.send({message}, 'click');` is not working:
![Screenshot 2024-09-25 at 9 33 53 PM](https://github.com/user-attachments/assets/120b4447-1521-44a0-8efb-d200d5067a83)

> Also do you think an options obj would be easier or harder to use?
> 
> e.g.
> 
> chatgpt.getChatData({ chat: 'latest', details: 'msg', sender: 'both', msg: 'latest' }) (can allow ordering options in any order)
> 
> vs. the current
> 
> chatgpt.getChatData('latest', 'msg', 'both', 'latest') (much shorter to type, but requires memorizing order of params)


Both are OK IMO, using params is easier to write.

**Comment by gadelkareem** [comment]
Thanks @adamlui for prompt response. I am not sure if it is on my end but now the `chatgpt.send({message}, 'click');` is not working:
![Screenshot 2024-09-25 at 9 33 53 PM](https://github.com/user-attachments/assets/120b4447-1521-44a0-8efb-d200d5067a83)

> Also do you think an options obj would be easier or harder to use?
> 
> e.g.
> 
> chatgpt.getChatData({ chat: 'latest', details: 'msg', sender: 'both', msg: 'latest' }) (can allow ordering options in any order)
> 
> vs. the current
> 
> chatgpt.getChatData('latest', 'msg', 'both', 'latest') (much shorter to type, but requires memorizing order of params)


Both are OK IMO, using params is easier to write.

**Comment by gadelkareem** [comment]
Thanks @adamlui for prompt response. I am not sure if it is on my end but now the `chatgpt.send({message}, 'click');` is not working:
![Screenshot 2024-09-25 at 9 33 53 PM](https://github.com/user-attachments/assets/120b4447-1521-44a0-8efb-d200d5067a83)

> Also do you think an options obj would be easier or harder to use?
> 
> e.g.
> 
> chatgpt.getChatData({ chat: 'latest', details: 'msg', sender: 'both', msg: 'latest' }) (can allow ordering options in any order)
> 
> vs. the current
> 
> chatgpt.getChatData('latest', 'msg', 'both', 'latest') (much shorter to type, but requires memorizing order of params)


Both are OK IMO, using params is easier to write.

**Comment by gadelkareem** [comment]
Thanks @adamlui for prompt response. I am not sure if it is on my end but now the `chatgpt.send({message}, 'click');` is not working:
![Screenshot 2024-09-25 at 9 33 53 PM](https://github.com/user-attachments/assets/120b4447-1521-44a0-8efb-d200d5067a83)

> Also do you think an options obj would be easier or harder to use?
> 
> e.g.
> 
> chatgpt.getChatData({ chat: 'latest', details: 'msg', sender: 'both', msg: 'latest' }) (can allow ordering options in any order)
> 
> vs. the current
> 
> chatgpt.getChatData('latest', 'msg', 'both', 'latest') (much shorter to type, but requires memorizing order of params)


Both are OK IMO, using params is easier to write.

**Comment by adamlui** [comment]
That's strange, I can't replicate, also the method is not async so the await isn't needed, but regardless IDK why that error is occurring

**Comment by gadelkareem** [comment]
You are right! Thank you for the fix!
