### ISSUE TITLE
getChatInput returns undefined

### ISSUE THREAD

**Issue by ae3e** [KudoAI/chatgpt.js#304]
Can't make getChatInput working or return the value of chatgpt.getChatBox().

But this code works :
```js
const chatbox = chatgpt.getChatBox()
chatbox .childNodes[0].innerText
```

**Comment by adamlui** [comment]
hey @ae3e thanks for reporting, it used to be textarea but now is div, it's updated to work again in [v3.3.3](https://github.com/KudoAI/chatgpt.js/releases/tag/v3.3.3)
