### ISSUE TITLE
Can you please create typescript type definitions?

### ISSUE THREAD

**Issue by grayfallstown** [KudoAI/chatgpt.js#349]
It would really help my IDE autocomplete and check for errors.

Great work on this project btw! ❤️

**Comment by grayfallstown** [comment]
Sorry, was blind

**Comment by adamlui** [comment]
> Sorry, was blind

What did you mean?

**Comment by grayfallstown** [comment]
> What did you mean?

found an index.d.ts in the node_module folder but just came back to the project and turned out it was the wrong chatgpt package

**Comment by souvikinator** [comment]
Hi! can we get a typescript type definitions for the package?
