### ISSUE TITLE
chatgpt.getLastResponse()  is getting always this response: '1 / 1'

### ISSUE THREAD

**Issue by madruga8** [kudoai/chatgpt.js#40]
chatgpt.getLastResponse()  is getting always this response: '1 / 1'

**Comment by adamlui** [comment]
hey @madruga8 I fixed it, it is updated to work in

`https://code.chatgptjs.org/chatgpt-latest.min.js` or
`https://cdn.jsdelivr.net/gh/chatgptjs/chatgpt.js@94fa613d4d564bb48e77ce715841d1641b954e51/dist/chatgpt-1.6.4.min.js` (required to publish to Greasy Fork)

also I would love to see your tool when you finish
