### ISSUE TITLE
Working on a new method

### ISSUE THREAD

**Issue by madkarmaa** [kudoai/chatgpt.js#63]
I'm working on a new method I want to call `getChatID`. what is it? basically a rewritten `fetch` function. this is what I got so far:

```js
// Needs to be called before document loading
const originalFetch = window.fetch;

window.fetch = function (url, options) {
  return originalFetch.apply(this, arguments)
    .then((response) => {
      if (response.url.includes('://chat.openai.com/backend-api/conversations')) {
        response.json().then((data) => { console.log(data); });
      }
      return response;
    });
};
```

the chat id is the url identifier

![image](https://github.com/kudoai/chatgpt.js/assets/100418457/3989a21a-38f2-45a0-9484-9e526f2c4465)

why rewriting fetch instead of splitting the url? because you can't get the current chat id unless you refresh the page

why am I opening the issue? because even tho it works (the chats ids are in the `items` object key)

![image](https://github.com/kudoai/chatgpt.js/assets/100418457/08262168-93d0-4c82-b4a5-5b5e582eec67)

it breaks the loading of conversations and I don't know how to fix it

![image](https://github.com/kudoai/chatgpt.js/assets/100418457/6dd34f26-cadc-4583-a494-818045d75f7f)

**Comment by madkarmaa** [comment]
only by converting the response to json it breaks, otherwise it doesn't

**Comment by adamlui** [comment]
@madkarmaa I'm working on some docs, i can check it out when I'm done

**Comment by madkarmaa** [comment]
@adamlui I've fixed it

```js
// Needs to be called before document loading
const originalFetch = window.fetch;

window.fetch = function (url, options) {
  return originalFetch.apply(this, arguments)
    .then((response) => {
      if (response.url.includes('://chat.openai.com/backend-api/conversations')) {
        var resp = response.clone();
        resp.json().then((data) => {
          if (data.items.length > 0) console.log(data.items[0].id);
          else console.error('🤖 chatgpt.js >> No chat history found!');
        });
      }
      return response;
    });
};
```

![image](https://github.com/kudoai/chatgpt.js/assets/100418457/559eab7b-3ab8-4ab5-8ac3-8cc5ac89aec5)

![image](https://github.com/kudoai/chatgpt.js/assets/100418457/9f4864e4-8e4a-4b79-92d7-5f11f2251c06)

now I need to know how we can add this to the library, because `fetch` needs to be re-written when the page loads, but also needs to set a value to a variable in the library which `getChatID` (or `getChatDetails` if you remove `.id` from `data.items[0].id`) can read

**Comment by adamlui** [comment]
Just add a function like any of the other ones that returns what the user seeks, no var's needed (i.e. getChatID returns data.items[0].id)

For anything needed before document load, you can type it anywhere in the library

**Comment by adamlui** [comment]
Because I can always move it for organization, the priority is it just works

**Comment by adamlui** [comment]
The custom functions can just call the fetch hook and pick the appropriate value from the response

**Comment by madkarmaa** [comment]
well thing is I don't know if it's possible to make the fetch request, right now as you can see I'm just listening to fetch requests going to that specific api endpoint. maybe fetching the endpoint with the library is not even needed since the website does it by itself each time you open a previous/new chat

**Comment by madkarmaa** [comment]
that is why I'm telling you a variable might be needed

**Comment by adamlui** [comment]
It would be useful on-demand instead of on open chats if user wants to getLastID at any moment, so creating a new fetch each time is ideal to evolve lib to a server-side one that can be used on any site

**Comment by madkarmaa** [comment]
ok, let me take a look at the headers of the request

**Comment by adamlui** [comment]
Because the way I marketed/named it makes users who don't read the description think it's an API wrapper, so user growth will be much bigger if we meet that perception

**Comment by madkarmaa** [comment]
```js
fetch('https://chat.openai.com/backend-api/conversations?offset=0&limit=28&order=updated')
  .then(response => response.json())
  .then(data => {
    // Process the response data here
    console.log(data);
  })
  .catch(error => {
    // Handle any errors that occur during the request
    console.error('Error:', error);
  });
```

![image](https://github.com/kudoai/chatgpt.js/assets/100418457/a2237a8d-dc0b-445f-9b52-fd8fe44d0d38)

**Comment by madkarmaa** [comment]
we will need to get the user's access token

**Comment by adamlui** [comment]
In my DDGPT and BraveGPT scripts I wrote a getAccessToken() you could look at

**Comment by adamlui** [comment]
btw yesterday's growth was because I posted to Hacker News and it hit the front page:

![image](https://github.com/kudoai/chatgpt.js/assets/10906554/a708d472-f43d-4689-8fb6-d5c0f8a02750)

We got ~45 stars / 305 visitors ~ 15% conversion rate which is quite low because most thought it is server-side lib. So I'm not marketing anymore until we evolve fully into that, and growth will be flatline for a while as a result

**Comment by adamlui** [comment]
Cuz hardcore hackers wanna interact back-end to build stand-alone apps

**Comment by adamlui** [comment]
Not-so-hard* for wanting to use a lib 😂

**Comment by adamlui** [comment]
...but reasonable to assume a lib called chatgpt.js meets that need. Imagine how op we'll be after conquering front and back ends...

**Comment by madkarmaa** [comment]
> In my DDGPT and BraveGPT scripts I wrote a getAccessToken() you could look at

I can't understand half the stuff you wrote in there 😂

**Comment by madkarmaa** [comment]
also because half the stuff uses the GM api, which we can't use in the library

**Comment by adamlui** [comment]
It's ok I have to eat a sandwich for protein because I have long covid and thhen I'll try to integrate with your code without using GM (there are equivalents in js) but i take a while to eat because of a past surgery I had so don't wait up

**Comment by madkarmaa** [comment]
sure, I'm just gonna play some minecraft, I'm also in my summer holidays away from school, so I have all the time in the world

**Comment by adamlui** [comment]
what grade are you? also for example GM.xmlHttpRequest is XMLHttpRequest() and fetch() can actually achieve the same (but less backwards compatible since it's newer)

**Comment by adamlui** [comment]
I use GM because it's always compatible with the userscript manager, also there's less CORS restriction in the context of how userscripts load

**Comment by madkarmaa** [comment]
> what grade are you?

based on a google search I'm 11th/12th (in my country we don't use this grade system)

> also for example GM.xmlHttpRequest is XMLHttpRequest() using different syntax and fetch() can actually achieve the same (but less backwards compatible since it's newer)

I use fetch because I'm dumb, and in either JavaScript or any C language, I always forget that I need the `new` keyword for objects

**Comment by adamlui** [comment]
Most people use newer things just like most people use a million lines the last time you said you were dumb to spread my condensed lines out, it's just I'm extra smart so don't think like most (i.e. few prioritize backwards compatibility)

**Comment by adamlui** [comment]
So it is simply normal to do things how I don't (and smart to do how I do) not dumb at all

**Comment by madkarmaa** [comment]
I can make the function myself, I just can't understand how you get the session token from the website, and how you set up the headers, just that, I would've completed this hours ago

**Comment by madkarmaa** [comment]
nvm, I got it(?) I'm still missing the body of the request.

```js
const sessionUrl = 'https://chat.openai.com/api/auth/session';
const chatUrl = 'https://chat.openai.com/backend-api/conversation';

async function getAccessToken() {
  const response = await fetch(sessionUrl);
  const data = await response.json();
  return data.accessToken;
}

const accessKey = await getAccessToken();

const headers = {
  'Content-Type': 'application/json',
  Authorization: 'Bearer ' + accessKey
};

const response = await fetch(chatUrl, { method: 'POST', headers: headers });
const data = await response.json();

console.log(data);
```

thing is, I'm not trying to get a response from chatgpt right here, that's why I was listening to requests instead of making one. this method does the same as duckduckgpt, but I'm trying to get the current chat's id, thing that doesn't have sense outside of the website itself

**Comment by adamlui** [comment]
I fell asleep and don't feel well cuz COVID so I'll look at it later

**Comment by madkarmaa** [comment]
nvm I'm stupid and the method needed was GET and not POST lol

```js
const sessionUrl = 'https://chat.openai.com/api/auth/session';
const chatUrl = 'https://chat.openai.com/backend-api/conversations';

async function getAccessToken() {
  const response = await fetch(sessionUrl);
  const data = await response.json();
  return data.accessToken;
}

const accessKey = await getAccessToken();

const headers = {
  'Content-Type': 'application/json',
  Authorization: 'Bearer ' + accessKey
};

const response = await fetch(chatUrl, { method: 'GET', headers: headers });
const data = await response.json();

console.log(data.items);
```

this will return all the chats. I'll now make it a XMLHttpRequest and create a method. before I proceed, do I need that cloudflare check?

**Comment by adamlui** [comment]
@madkarmaa what cloudflare check?

**Comment by madkarmaa** [comment]
> @madkarmaa what cloudflare check?

https://github.com/kudoai/duckduckgpt/blob/main/greasemonkey/duckduckgpt.user.js#L211-L217

also, this is what a chat data object looks like. is there anything else that would be needed other than the id?

![image](https://github.com/kudoai/chatgpt.js/assets/100418457/e0f84bfd-4b70-4acb-978b-d1f29870eb6a)

**Comment by adamlui** [comment]
The `isBlockedByCloudflare` just gives a more tailored alert in sidebar which isn't needed for a lib user

> also, this is what a chat data object looks like. is there anything else that would be needed other than the id?

Yes you should make `getChatTitle` too

**Comment by madkarmaa** [comment]
> Yes you should make `getChatTitle` too

latest only or indexed? (`pos` parameter)

**Comment by adamlui** [comment]
Both would be good, also `getChatTitle(id)` maybe

**Comment by adamlui** [comment]
However you would most use it is the prioritized minimally viable way

**Comment by adamlui** [comment]
Then once that works, adding other features can be slowly done

**Comment by madkarmaa** [comment]
this is the current code
```js
    getChatDetails: function(idx = 0, detail = 'id') {
        const sessionUrl = 'https://chat.openai.com/api/auth/session';
        const chatUrl = 'https://chat.openai.com/backend-api/conversations';
        
        function getAccessToken() {
            return new Promise((resolve) => {
                const xhr = new XMLHttpRequest();
                xhr.open('GET', sessionUrl, true);
                xhr.setRequestHeader('Content-Type', 'application/json');
                xhr.onload = function() {
                    if (xhr.status === 200) {
                        resolve(JSON.parse(xhr.responseText).accessToken);
                    } else {
                        console.error('🤖 chatgpt.js >> Request failed. Cannot retrieve access token.');
                    }
                };
                xhr.send();
            });
        }

        getAccessToken().then(token => {

        });
    },
```

I don't know how to implement the following

```js
            return new Promise((resolve) => {
                const xhr = new XMLHttpRequest();
                xhr.open('GET', chatUrl, true);
                xhr.setRequestHeader('Content-Type', 'application/json');
                xhr.setRequestHeader('Authorization', 'Bearer ' + token);
                xhr.onload = function() {
                    if (xhr.status === 200) {
                        resolve(JSON.parse(xhr.responseText)[idx][detail]);
                    } else {
                        console.error('🤖 chatgpt.js >> Request failed. Cannot retrieve chat details.');
                    }
                };
                xhr.send();
            });
```

**Comment by adamlui** [comment]
Ok I'll try after I finish some more docs

**Comment by madkarmaa** [comment]
nvm I'm just dumb
