### ISSUE TITLE
Add access token management

### ISSUE THREAD

**Issue by adamlui** [kudoai/chatgpt.js#83]
also (this is just an idea of mine), I think we should store an access token somewhere in the chatgpt object as a variable, and update it once it expires (the token has an expiration date, reference [here](https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L379)) to avoid getting rate limited by the api and reducing the speed of the library

problem is idk about the security of doing this

edit: it shouldn't even matter since there's literally a function that retrieves the access token, so storing it in the object is not even a big deal, and removing the object from the window will literally make it disappear

_Originally posted by @madkarmaa in https://github.com/kudoai/chatgpt.js/issues/79#issuecomment-1634781262_

**Comment by madkarmaa** [comment]
what do you think

**Comment by adamlui** [comment]
Yes it can be stored using local storage, then I have to update docs to require that permission for platforms like chrome

**Comment by adamlui** [comment]
I just woke up and just worked on your awesome getResponseFromAPI without eating, so I have to eat first though (then I'ma rename getResponse to getResponseFromDOM, then re-add getResponse using conditional logic)

You could get started on editing getAccessToken if you want, you could look at DDGPT/bravegpt to see how storage is implemented

**Comment by madkarmaa** [comment]
isn't localStorage too easy to access? also, it is permanent (until removed by the user). I know it's easy to get the access token, but that'll literally store it globally and it'll become avaiable for whatever extension or userscript or javascript injection that interactly with the website

**Comment by adamlui** [comment]
Yes it is permanent which is fine if getAccessToken is edited to return stored value and on error replaces it (like my webgpt scripts do)

Re global access it doesn't matter, if the key is named openAIaccessToken and some other app relies on storage for such a key, we are doing them a favor by providing it

**Comment by adamlui** [comment]
(and the GM methods can be replaced with JS equivalents)

**Comment by adamlui** [comment]
@madkarmaa actually in hindsight your storing it in `chatgpt` obj is better since user won't need additional permissions, so stores like Chrome will approve more leniently!

**Comment by adamlui** [comment]
This is an example of how hasty they are to reject even extensions that are Featured from Verified publishers:

![image](https://github.com/kudoai/chatgpt.js/assets/10906554/1972c312-c752-4860-84fd-24c737c63d87)

**Comment by adamlui** [comment]
I clapped back with a Karen email and got them to apologize though 😂

![image](https://github.com/kudoai/chatgpt.js/assets/10906554/da6f2dd2-433d-4f4a-9fde-e2499a21b6f3)

**Comment by adamlui** [comment]
This the karen email I sent to get the apology:

> The reviewer falsely accuses me of "mimicking ranking" for including a badge on tiles that ChatGPT Widescreen received #2 Product of the Week on Product Hunt.
> 
> However, it is not "mimicking" if it factually occurred.
> 
> Here is the email received confirming this ranking: https://imgur.com/lyZh6La
> 
> Also, if you go to https://www.producthunt.com/products/chatgpt-widescreen-mode/awards, you will note it clearly says "1 Badges" (you don't get that awarded if you didn't rank in top 5)
> 
> The corrective action demanded of me by this reviewer is to "Remove the content that is mimicking ranking," however this statement in itself is inaccurate as no mimicry is occurring. The badge is provided by Product Hunt, clearly showing Product Hunt logo, and I am using it as intended in a 100% honest manner. Please remove this violation from my account as **I am a man of great honor**.

**Comment by madkarmaa** [comment]
bruh 💀

**Comment by adamlui** [comment]
One with honor must fight for honor (one without is justifiably rejected)

**Comment by madkarmaa** [comment]
> @madkarmaa actually in hindsight your storing it in `chatgpt` obj is better since user won't need additional permissions, so stores like Chrome will approve more leniently!

there we go, PR #84
