### ISSUE TITLE
Non-async functions

### ISSUE THREAD

**Issue by madkarmaa** [kudoai/chatgpt.js#90]
https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L480
https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L488
https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L510

the above lines treat asynchronous functions as normal ones

**Comment by madkarmaa** [comment]
also, there's a whole lot of `get*Response*()` methods, and I think it's actually really confusing

I'm not talking as a~~n experienced~~ programmer, but as a normal library user. I'd actually get a whole lot confused by all those methods that look a lot similar to each other

just saying, but you can keep it as is, the project is yours not mine

**Comment by adamlui** [comment]
> https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L480 https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L488 https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L510
> 
> the above lines treat asynchronous functions as normal ones

No they don't they still return promises, just type

```js
    const lastResponse = await chatgpt.getLastResponse()
    console.log(lastResponse)
```

and observe your log

**Comment by madkarmaa** [comment]
> > https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L480 https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L488 https://github.com/kudoai/chatgpt.js/blob/main/chatgpt.js#L510
> > the above lines treat asynchronous functions as normal ones
> 
> No they don't they still return promises, just edit the condition to change 'chat.openai.com' into some random URL, then type
> 
> ```js
>     const lastResponse = await chatgpt.getLastResponse()
>     console.log(lastResponse)
> ```
> 
> ...to call chatgpt.getResponseFromAPI() and observe your log

ohhh cool, didn't know that

**Comment by adamlui** [comment]
> also, there's a whole lot of `get*Response*()` methods, and I think it's actually really confusing
> 
> I'm not talking as a~n experienced~ programmer, but as a normal library user. I'd actually get a whole lot confused by all those methods that look a lot similar to each other
> 
> just saying, but you can keep it as is, the project is yours not mine

Well you added getReseponseFromAPI so getResponse had to change to also include it, I'll add notes to clear it up

**Comment by madkarmaa** [comment]
> Well you added getReseponseFromAPI so getResponse had to change to also include it, I'll add notes to clear it up

okay but isn't this

![image](https://github.com/kudoai/chatgpt.js/assets/100418457/324113b0-60de-4dba-adf3-e40deb5e0321)
![image](https://github.com/kudoai/chatgpt.js/assets/100418457/31fbc6f7-ff90-4644-9d85-2a12a6316fa5)

a littly too much?

**Comment by adamlui** [comment]
I don't understand your question

**Comment by adamlui** [comment]
What is it you want to delete? Other people added functions they use in their popular scripts and may find yours too much

**Comment by adamlui** [comment]
The getlastresponses are used in popular userscripts before you ever added fromapi so if you think about it, you made it too much not them (they added before you not other way around)

**Comment by adamlui** [comment]
Just because I rename it doesn't mean it didn't exist before you

**Comment by adamlui** [comment]
I renamed it to accommodate yours and now you call theirs too much, this is a jokd

**Comment by adamlui** [comment]
i.e. the other functions already yielded for yours, it's not right to demand their complete removal. They are used in popular scripts you're not the only lib user

**Comment by adamlui** [comment]
I know you initially respected their existence by adding not replacing but now you are being really greedy and overcritical

**Comment by madkarmaa** [comment]
nope, that's not what I said, and I'm just looking at how many there are and thinking if there's any way to make them more easy to understand

**Comment by adamlui** [comment]
And I told you I'll add comments, I was busy patching printallfunctions which broke when you added openAIaccessToken as undefined. But clearly that was not acceptable solution to you for pressing the issue like you want them gone

**Comment by madkarmaa** [comment]
> I know you initially respected their existence by adding not replacing but now you are being really greedy and overcritical

sorry, leave it, I was just wondering how to make them easy to understand and not to remove them. as I said, they look a lot _similar_ to each other, not that I want to remove them, absolutely. and I get your point, as I said

> just saying, but you can keep it as is, the project is yours not mine

**Comment by adamlui** [comment]
It's not mine it's everyone's who uses it and I'm trying to get you to see that

**Comment by adamlui** [comment]
You said it was "too much" but not exactly if it's already being used with no confusion by users that are not you or me

**Comment by adamlui** [comment]
Also "too much" implies addition, these were pre-existing, understood methods before addition of the API methods

**Comment by madkarmaa** [comment]
I get you point, it was an opinion of mine, I didn't want it to be accepted

**Comment by adamlui** [comment]
Didn't want what accepted

**Comment by madkarmaa** [comment]
my opinion on the thing being confusing, since it was me being a little confused and not you or anybody else. I explained my personal opinion, not asking for it to be accepted or expecting anything in the library to change

**Comment by adamlui** [comment]
It was accepted though, they now need the change of comments to distinguish from your added API method, which I presented as a solution, but you still called them too much implying you want them gone, is that not your solution?

**Comment by madkarmaa** [comment]
it isn't, I haven't implied any removal, in fact, I haven't implied any solution at all, I was just explaining my opinion

**Comment by adamlui** [comment]
So your opinion is the pre-existing methods before yours which were understood by others are too confusing even with comments therefore are "too much" to coexist with yours

**Comment by adamlui** [comment]
Because when you added yours they weren't too much until I added the general ones to call yours and theirs

**Comment by adamlui** [comment]
So which ones you want gone the dom methods or the general ones

**Comment by madkarmaa** [comment]
no, my opinion was that the names are too similar to each other, nothing implying "_mine_" or "_yours_" since I just want to contribute and by contributing there's no thing such as "_mine_", that was the point of the screenshots. but now that I've been thinking about it, there's no way to change them since their names explain what they do. so please, leave this, I was just being confused

**Comment by adamlui** [comment]
well a lot of users are using the DOM vesrions already so I had to change them to general ones to call the API ones you like since it's not strictly DOM method anymore

**Comment by adamlui** [comment]
or I can revert but getResponse = DOM and getResponseFromAPI = API is not very parallel

**Comment by madkarmaa** [comment]
yes surely, I now get your point. I didn't ask anything to change, and I **do not** want anything to change. I've said that because I've synced my fork and got greeted with all the changes in the commit 4caba80, which confused me a little. I've spent a little trying to figure out what everything does, and got a little confused. but now, a few hours later, I've understood

**Comment by madkarmaa** [comment]
thanks for the understanding, and I'm sorry if I caused any trouble between us
